### ISSUE TITLE
Unable to change colour on Goove Immersion (H6199)

### ISSUE THREAD

**Issue by calvinyeap** [bwp91/homebridge-govee#116]
Hi there, I have managed to setup the plugin and able to on/off and adjust brightness but however having issue to change the colour via homekit. I have inserted by API key and credentials as well. Is there anything I should check?

**Comment by bwp91** [comment]
Can you use the plugin settings to turn on debug mode, and then copy and paste the homebridge logs that appear when you try to change colour?

Making a distinction between the colour wheel and the colour temperature, does either of them
work?

**Comment by calvinyeap** [comment]
Hi Ben, I treid both and strangely it worked a few of times but not all the time. Here's the log file. Does this help?

[09/09/2021, 20:22:07] [Govee] [Ambient Light] current colour [rgb 209 255 213].
[09/09/2021, 20:22:09] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":"false","powerState":"on","brightness":100,"color":{"r":255,"b":183,"g":100}}].
[09/09/2021, 20:22:24] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":255,"b":183,"g":100}}].
[09/09/2021, 20:22:39] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":255,"b":183,"g":100}}].

**Comment by calvinyeap** [comment]
Btw Ben, I have also updated my node.js frm v12 to v14 using this command "sudo hb-service update-node ".

  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'

And I'm now getting this warning when loading the plugin.

[09/09/2021, 20:29:57] [Govee] Disabling BLE client as The module '/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).was compiled against a different Node.js version using.

**Comment by bwp91** [comment]
> Btw Ben, I have also updated my node.js frm v12 to v14 using this command "sudo hb-service update-node ".
> 
> npm: '6.14.15',
> ares: '1.17.2',
> brotli: '1.0.9',
> cldr: '39.0',
> icu: '69.1',
> llhttp: '2.1.3',
> modules: '83',
> napi: '8',
> nghttp2: '1.42.0',
> node: '14.17.6',
> openssl: '1.1.1l',
> tz: '2021a',
> unicode: '13.0',
> uv: '1.41.0',
> v8: '8.4.371.23-node.76',
> zlib: '1.2.11'
> 
> And I'm now getting this warning when loading the plugin.
> 
> [09/09/2021, 20:29:57] [Govee] Disabling BLE client as The module '/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION 72. This version of Node.js requires
> NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).was compiled against a different Node.js version using.

A plugin reinstall should solve this, run this in the terminal:

```
sudo npm i -g homebridge-govee
```

**Comment by calvinyeap** [comment]
Thanks Ben but,reinstall didn't worked for me. I've uninstall and install the plugin again and it worked and the earlier warning message is now gone. However I'm still unable to change the colour though. Is there something I should check further?

[09/09/2021, 21:00:21] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631192421345","type":1,"cmd":"color","data":{"r":51,"g":248,"b":255,"red":51,"green":248,"blue":255},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[09/09/2021, 21:00:21] [Govee] [Ambient Light] current colour [rgb 51 248 255].
[09/09/2021, 21:00:26] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":4,"b":255,"g":0}}].

**Comment by bwp91** [comment]
When you control the light, you should see log messages that appear with `sending update…` and then after that a couple of `receiving update…` messages.
It would be useful to see the sending and receiving messages for an instance that it doesn’t work.

Have you set the plugin up to use bluetooth for this light? (if the light supports it?)

**Comment by calvinyeap** [comment]
Hi Ben, I have enabled Bluetooth and it works for a couple of times and then it freezes my light strip and I’m unable to control using Govee app as well. Then I would have to reboot the light strip. Without Bluetooth, I’m able to control reliably the power state and brightness but unable to change colour. This is the log when I’m connecting using Bluetooth but in this instance it wasn’t successful in changing the colour as well.

![IMG_0253](https://user-images.githubusercontent.com/60149048/132842453-acb01dd3-cf07-4c32-aec1-3ff5168b56ea.png)

**Comment by bwp91** [comment]
Try disabling the bluetooth through the plugin… your device supports AWS connection and this can be even more reliable than bluetooth.

The AWS goes through wifi.

It’s important that the light isn’t connected to bluetooth on your phone (via the govee app) when controlling the device though AWS via the plugin. These lights seem to not bother maintaining the wifi connection when the bluetooth is connected.

So just try disabling the plugin bluetooth and also disabling bluetooth on your phone (for the purpose of testing). Then try changing the colour of the light strip via the home app.

If it still doesn’t work, I can get you to provide some more debug info.

**Comment by calvinyeap** [comment]
Hi Ben, i did the following test.
1. Disable BLE, enable AWS and API - unable to change colour
2. DIsable BLE and API, enable AWS - unable to work at all and the following is log file

```
[10/09/2021, 19:56:36] [Govee] Disabling API client as API key not provided.
[10/09/2021, 19:56:36] [Govee] Disabling BLE client as no enabled devices configured.
[10/09/2021, 19:56:37] [Govee] [Ambient Light] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"no","logging":"debug"}.
[10/09/2021, 19:56:37] [Govee] [Ambient Light] initialised with id [0A:B0:A4:C1:38:3A:44:E9].
[10/09/2021, 19:56:37] [Govee] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
[10/09/2021, 19:56:37] [Govee] [Ambient Light] has been reported [offline] via API, so update may or may not be successful.
[10/09/2021, 19:56:37] [Govee] [Ambient Light] not sending AWS update as not connected to AWS at connectionAWS.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/aws.js:112:13).
[10/09/2021, 19:56:37] [Govee] [Ambient Light] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1029:17.
[10/09/2021, 19:56:38] [Govee] [Ambient Light] [AWS] connected event.
[10/09/2021, 19:57:33] [Govee] [Ambient Light] has been reported [offline] via API, so update may or may not be successful.
[10/09/2021, 19:57:33] [Govee] [Ambient Light] [AWS] sending update {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631275053183000","type":1}}.
[10/09/2021, 19:57:33] [Govee] [Ambient Light] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1029:17.
[10/09/2021, 19:57:33] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631275053183000","type":1}}].
[10/09/2021, 19:57:33] [Govee] [Ambient Light] [AWS] receiving update [{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631275053183000","type":1,"source":"AWS"}].
[10/09/2021, 19:57:37] [Govee] [Ambient Light] has been reported [offline] via API, so update may or may not be successful.
[10/09/2021, 19:57:37] [Govee] [Ambient Light] [AWS] sending update {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"colorTem","cmdVersion":0,"data":{"color":{"red":255,"green":195,"blue":124},"colorTemInKelvin":3300},"transaction":"v_1631275057485000","type":1}}.
[10/09/2021, 19:57:37] [Govee] [Ambient Light] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1029:17.
[10/09/2021, 19:57:37] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"colorTem","cmdVersion":0,"data":{"color":{"red":255,"green":195,"blue":124},"colorTemInKelvin":3300},"transaction":"v_1631275057485000","type":1}}].
[10/09/2021, 19:57:37] [Govee] [Ambient Light] [AWS] receiving update [{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"colorTem","cmdVersion":0,"data":{"color":{"red":255,"green":195,"blue":124},"colorTemInKelvin":3300},"transaction":"v_1631275057485000","type":1,"source":"AWS"}].
```

3. Disable BLE & AWS, enabled API only - VOILA, it works without any issues. But in this case, how do i use custome scene ya?

**Comment by bwp91** [comment]
In the plugin settings screen, on the “my devices” tab, what does is say for the supported commands for this device?

Also can you send me a screenshow of how this device looks in the govee app? the page to control the colours

**Comment by calvinyeap** [comment]
Hi Ben, here you go 😃
![6AF31B38-F57F-47A4-86E7-9C4EB21B6D6C](https://user-images.githubusercontent.com/60149048/132856274-1c246056-8459-401c-9294-471e2370bae7.png)
![E3E87707-7927-46B3-8DC1-79CA84969AA8](https://user-images.githubusercontent.com/60149048/132856286-8db710f9-d649-4d41-92f1-e69d4d4f4482.png)
![7138C719-E6C6-4DB7-9AD8-BC92E39EF258](https://user-images.githubusercontent.com/60149048/132856309-d257e152-8e3f-4927-b87d-bb684448c34e.png)

**Comment by bwp91** [comment]
Does it work with AWS enabled to change the colour? by colour I literally mean a colour like red, blue, not the colour temperature.

**Comment by bwp91** [comment]
Test with both AWS and API enabled

**Comment by calvinyeap** [comment]
With AWS and API both enabled, I'm able to control power on/off but not colour. The following shows I turn it on and then try to change from red to blue. "Sending Update" via both AWS and API but "Receive Update" in AWS shows colour changed to blue but in API colour remain in red. In actual the light remain in red and didn't change to blue. Here's the log.

[10/09/2021, 21:42:27] [Govee] [Ambient Light] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"disableAWS":"no","enableBT":"no","logging":"debug"}.
[10/09/2021, 21:42:27] [Govee] [Ambient Light] initialised with id [0A:B0:A4:C1:38:3A:44:E9].
[10/09/2021, 21:42:28] [Govee] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
[10/09/2021, 21:42:28] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":50,"color":{"r":255,"b":0,"g":0}}].
[10/09/2021, 21:42:28] [Govee] [Ambient Light] has been reported [online].
[10/09/2021, 21:42:29] [Govee] [Ambient Light] [AWS] connected event.
[10/09/2021, 21:42:35] [Govee] [Ambient Light] [AWS] sending update {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631281355758000","type":1}}.
[10/09/2021, 21:42:35] [Govee] [Ambient Light] [API] sending update {"name":"turn","value":"off"}.
[10/09/2021, 21:42:36] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631281355758000","type":1}}].
[10/09/2021, 21:42:36] [Govee] [Ambient Light] [AWS] receiving update [{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":0},"transaction":"v_1631281355758000","type":1,"source":"AWS"}].
[10/09/2021, 21:42:36] [Govee] [Ambient Light] current state [off].
[10/09/2021, 21:42:36] [Govee] [Ambient Light] current state [off].
[10/09/2021, 21:42:36] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"o_1631281356769","type":1,"cmd":"turn","data":{"val":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810"}}].
[10/09/2021, 21:42:36] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631281356769","type":1,"cmd":"turn","data":{"val":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[10/09/2021, 21:42:43] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"off","brightness":50,"color":{"r":255,"b":0,"g":0}}].
[10/09/2021, 21:42:45] [Govee] [Ambient Light] [AWS] sending update {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631281365143000","type":1}}.
[10/09/2021, 21:42:45] [Govee] [Ambient Light] [API] sending update {"name":"turn","value":"on"}.
[10/09/2021, 21:42:45] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631281365143000","type":1}}].
[10/09/2021, 21:42:45] [Govee] [Ambient Light] [AWS] receiving update [{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631281365143000","type":1,"source":"AWS"}].
[10/09/2021, 21:42:45] [Govee] [Ambient Light] current state [on].
[10/09/2021, 21:42:46] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"o_1631281366374","type":1,"cmd":"turn","data":{"val":1},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810"}}].
[10/09/2021, 21:42:46] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631281366374","type":1,"cmd":"turn","data":{"val":1},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[10/09/2021, 21:42:46] [Govee] [Ambient Light] current state [on].
[10/09/2021, 21:42:53] [Govee] [Ambient Light] [AWS] sending update {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"color","cmdVersion":0,"data":{"red":0,"green":0,"blue":255},"transaction":"v_1631281373613000","type":1}}.
[10/09/2021, 21:42:53] [Govee] [Ambient Light] [API] sending update {"name":"color","value":{"r":0,"g":0,"b":255}}.
[10/09/2021, 21:42:53] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"color","cmdVersion":0,"data":{"red":0,"green":0,"blue":255},"transaction":"v_1631281373613000","type":1}}].
[10/09/2021, 21:42:53] [Govee] [Ambient Light] [AWS] receiving update [{"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","cmd":"color","cmdVersion":0,"data":{"red":0,"green":0,"blue":255},"transaction":"v_1631281373613000","type":1,"source":"AWS"}].
[10/09/2021, 21:42:53] [Govee] [Ambient Light] current colour [rgb 0 0 255].
[10/09/2021, 21:42:55] [Govee] [Ambient Light] current colour [rgb 0 0 255].
[10/09/2021, 21:42:55] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"o_1631281374971","type":1,"cmd":"color","data":{"r":0,"g":0,"b":255,"red":0,"green":0,"blue":255},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810"}}].
[10/09/2021, 21:42:55] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631281374971","type":1,"cmd":"color","data":{"r":0,"g":0,"b":255,"red":0,"green":0,"blue":255},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[10/09/2021, 21:42:58] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":"false","powerState":"on","brightness":50,"color":{"r":255,"b":0,"g":0}}].
[10/09/2021, 21:43:01] [Homebridge UI] Terminal session ended.

**Comment by calvinyeap** [comment]
And here is the log showing the update in AWS when i change the colour to blue via Govee app and subsequent update API show it's updated to blue.

[10/09/2021, 21:49:47] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"v_1631281787369817","data":{"value":["MwULAAD\/AAD\/fwAAAAAAAAAAAEI="]},"accountTopic":"GA\/d133f28c6d14b65f3e1944a80353a810","type":1,"cmdVersion":0,"cmd":"bulb"}}].
[10/09/2021, 21:49:59] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":50,"color":{"r":0,"b":255,"g":0}}].
[10/09/2021, 21:49:59] [Govee] [Ambient Light] current colour [rgb 0 0 255].
[10/09/2021, 21:50:18] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":50,"color":{"r":0,"b":255,"g":0}}].

**Comment by bwp91** [comment]
Can you try in the govee app turning “gradient” off and turning to blue and post the logs of what appear?

**Comment by calvinyeap** [comment]
Here you go, with the gradient option off.

[10/09/2021, 23:00:21] [Govee] [Ambient Light] [AWS] connected event.
[10/09/2021, 23:00:21] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":0,"b":0,"g":255}}].
[10/09/2021, 23:00:21] [Govee] [Ambient Light] has been reported [online].
[10/09/2021, 23:00:32] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"v_1631286032639679","data":{"value":["MwULAAD\/AAD\/fwAAAAAAAAAAAEI="]},"accountTopic":"GA\/d133f28c6d14b65f3e1944a80353a810","type":1,"cmdVersion":0,"cmd":"bulb"}}].
[10/09/2021, 23:00:36] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":0,"b":255,"g":0}}].
[10/09/2021, 23:00:36] [Govee] [Ambient Light] current colour [rgb 0 0 255].
[10/09/2021, 23:00:50] [Govee] [Ambient Light] [API] receiving update [{"source":"API","online":true,"powerState":"on","brightness":100,"color":{"r":0,"b":255,"g":0}}].

**Comment by bwp91** [comment]
Can you update the plugin to beta version 4.10.1-beta.1, with AWS and API still enabled, to see if this helps?

**Comment by calvinyeap** [comment]
Sure, can you guide me how to update? What's the command ya?

**Comment by bwp91** [comment]
Yes, depends on the platform but this should help:

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by calvinyeap** [comment]
Wohoooooo, its working now! :)

[10/09/2021, 23:31:04] [Govee] [Ambient Light] not sending AWS update as command not supported via AWS.
[10/09/2021, 23:31:04] [Govee] [Ambient Light] [API] sending update {"name":"color","value":{"r":255,"g":0,"b":0}}.
[10/09/2021, 23:31:05] [Govee] Skipping sync as client is busy sending updates.
[10/09/2021, 23:31:05] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"o_1631287865575","type":1,"cmd":"color","data":{"r":255,"g":0,"b":0,"red":255,"green":0,"blue":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810"}}].
[10/09/2021, 23:31:05] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631287865575","type":1,"cmd":"color","data":{"r":255,"g":0,"b":0,"red":255,"green":0,"blue":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[10/09/2021, 23:31:05] [Govee] [Ambient Light] current colour [rgb 255 0 0].
[10/09/2021, 23:31:13] [Govee] [Ambient Light] not sending AWS update as command not supported via AWS.
[10/09/2021, 23:31:13] [Govee] [Ambient Light] [API] sending update {"name":"color","value":{"r":0,"g":255,"b":0}}.
[10/09/2021, 23:31:15] [Govee] [Ambient Light] current colour [rgb 0 255 0].
[10/09/2021, 23:31:15] [Govee] [Ambient Light] [AWS] message event [GD/d6d7d71020c591a4ab0ce361e3505907 {"msg":{"transaction":"o_1631287874945","type":1,"cmd":"color","data":{"r":0,"g":255,"b":0,"red":0,"green":255,"blue":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810"}}].
[10/09/2021, 23:31:15] [Govee] [Ambient Light] [AWS] receiving update [{"transaction":"o_1631287874945","type":1,"cmd":"color","data":{"r":0,"g":255,"b":0,"red":0,"green":255,"blue":0},"accountTopic":"GA/d133f28c6d14b65f3e1944a80353a810","source":"AWS"}].
[10/09/2021, 23:31:21] [Govee] [Ambient Light] [API

**Comment by bwp91** [comment]
In fact you should find you don’t have issues with bluetooth as well now.
But what i’ve done allows you to use the scenes via AWS too.

**Comment by calvinyeap** [comment]
Ahh yessss!! Thank you so much Ben, appreciate it..!! :)

**Comment by bwp91** [comment]
Background info, it seems that this model H6199 doesn’t accept the standard commands for colour and colour temperature over bluetooth and aws connection. Out of *all* the govee models, this is the first time I have seen this.

I believe this is why it was crashing your lights when bluetooth was on.

So the changes I have made are to skip bluetooth and aws commands when changing colour and colour temperature so it reverts straight to the API as this still seems to work.

And on/off and brightness will still be sent via bluetooth/aws when possible.

Makes me wonder if there are any other models that follow this pattern!

Glad this seems resolved, albeit more a workaround than a fix!

Edit, thanks for alerting me of this and thanks for your support :)

**Comment by calvinyeap** [comment]
Thanks again Ben, just tested with bluetooth enabled as well, no issues whatsoever! :)
