### ISSUE TITLE
H6056 brightness not working correctly. 100% brightness says 39% on Apple Home.

### ISSUE THREAD

**Issue by Matt-JGH** [bwp91/homebridge-govee#343]
### What issue do you have? Please be as thorough and explicit as possible.
Changing the brightness on the Home app to 100% puts the lights at 100%, but the home app displays it as 39%.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?
v4.50.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ubuntu Server
NPM = 8.13.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v7.1.1. Tried old betas but no change.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6056

### Please paste any relevant logs below.

```
[29/10/2022, 19:12:41] [Govee] [LAN] server started listening on 0.0.0.0:4002.
[29/10/2022, 19:12:41] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 1876) is running on port 51560.
[29/10/2022, 19:12:41] [Govee] [LAN] found device [{"msg":{"cmd":"scan","data":{"ip":"192.168.1.87","device":"CC:4E:C8:39:37:39:39:16","sku":"H6056","bleVersionHard":"3.02.01","bleVersionSoft":"1.09.07","wifiVersionHard":"1.00.11","wifiVersionSoft":"1.02.11"}}}] [{"address":"192.168.1.87","family":"IPv4","port":60339,"size":210}].
[29/10/2022, 19:12:43] [Govee] [LAN] client enabled and found 1 device(s).
[29/10/2022, 19:12:43] [Govee] [HTTP] retrieved access token from cache.
[29/10/2022, 19:12:44] [Govee] [HTTP] client enabled and found 1 device(s).
[29/10/2022, 19:12:44] [Govee] [AWS] client enabled.
[29/10/2022, 19:12:44] [Govee] [AWS] connect event.
[29/10/2022, 19:12:45] [Govee] [API] client enabled and found 1 device(s).
[29/10/2022, 19:12:47] [Govee] [BLE] disabling client as ENODEV, No such device.
[29/10/2022, 19:12:47] [Govee] [Bedroom Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[29/10/2022, 19:12:47] [Govee] [Bedroom Lights] initialised with id [CC:4E:C8:39:37:39:39:16] [H6056].
[29/10/2022, 19:12:47] [Govee] [Bedroom Lights] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667067167328000","type":0}}.
[29/10/2022, 19:12:48] [Govee] [Bedroom Lights] [API] receiving update {"online":true,"powerState":"on","brightness":96,"color":{"r":0,"b":255,"g":4},"source":"API"}.
[29/10/2022, 19:12:48] [Govee] [Bedroom Lights] has been reported [online].
[29/10/2022, 19:12:48] [Govee] [Bedroom Lights] current brightness [96%].
[29/10/2022, 19:12:49] [Govee] ✓ Setup complete. Want to see this plugin in your own language? Let me know!
[29/10/2022, 19:12:49] [Govee] [AWS] message event [{"proType":2,"sku":"H6056","device":"CC:4E:C8:39:37:39:39:16","softVersion":"1.09.07","wifiSoftVersion":"1.02.11","wifiHardVersion":"1.00.11","cmd":"status","type":0,"transaction":"v_1667067167328000","pactType":2,"pactCode":1,"state":{"onOff":1,"brightness":96,"colorTemInKelvin":0,"color":{"r":0,"g":4,"b":255},"mode":21,"result":1},"op":{"command":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZAAE/2QABP9kAAT/ZAAE/w4=","qqUCZAAE/2QABP9kAAT/ZAAE/w0=","qqUDZAAE/2QABP9kAAT/ZAAE/ww=","qhEAZAoKAAAAAAAAAAAAAAAAAN8=","qhIAZAgAAB4AAAAAAAAAAAAAAMo=","qiP/AAwAAAAAAIAAAACAAAAAgPo=","qjMRAAAAAAAAAAAAAAAAAAAAAIg="]}}].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] [AWS] receiving update {"onOff":1,"brightness":96,"colorTemInKelvin":0,"color":{"r":0,"g":4,"b":255},"mode":21,"result":1,"source":"AWS","commands":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZAAE/2QABP9kAAT/ZAAE/w4=","qqUCZAAE/2QABP9kAAT/ZAAE/w0=","qqUDZAAE/2QABP9kAAT/ZAAE/ww=","qhEAZAoKAAAAAAAAAAAAAAAAAN8=","qhIAZAgAAB4AAAAAAAAAAAAAAMo=","qiP/AAwAAAAAAIAAAACAAAAAgPo=","qjMRAAAAAAAAAAAAAAAAAAAAAIg="]}.
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] current brightness [38%].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qgUVAQAAAAAAAAAAAAAAAAAAALs=] [aa051501000000000000000000000000000000bb].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qqUBZAAE/2QABP9kAAT/ZAAE/w4=] [aaa501640004ff640004ff640004ff640004ff0e].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qqUCZAAE/2QABP9kAAT/ZAAE/w0=] [aaa502640004ff640004ff640004ff640004ff0d].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qqUDZAAE/2QABP9kAAT/ZAAE/ww=] [aaa503640004ff640004ff640004ff640004ff0c].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qhEAZAoKAAAAAAAAAAAAAAAAAN8=] [aa1100640a0a00000000000000000000000000df].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qhIAZAgAAB4AAAAAAAAAAAAAAMo=] [aa1200640800001e0000000000000000000000ca].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qiP/AAwAAAAAAIAAAACAAAAAgPo=] [aa23ff000c0000000000800000008000000080fa].
[29/10/2022, 19:12:49] [Govee] [Bedroom Lights] new scene code: [qjMRAAAAAAAAAAAAAAAAAAAAAIg=] [aa33110000000000000000000000000000000088].
[29/10/2022, 19:13:17] [Govee] [Bedroom Lights] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667067197343000","type":0}}.
[29/10/2022, 19:13:17] [Govee] [Bedroom Lights] [LAN] receiving update {"onOff":1,"brightness":96,"color":{"r":0,"g":4,"b":255},"colorTemInKelvin":0,"source":"LAN"}.
[29/10/2022, 19:13:17] [Govee] [Bedroom Lights] current brightness [96%].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] [API] receiving update {"online":true,"powerState":"on","brightness":96,"color":{"r":0,"b":255,"g":4},"source":"API"}.
[29/10/2022, 19:13:18] [Govee] [AWS] message event [{"proType":2,"sku":"H6056","device":"CC:4E:C8:39:37:39:39:16","softVersion":"1.09.07","wifiSoftVersion":"1.02.11","wifiHardVersion":"1.00.11","cmd":"status","type":0,"transaction":"v_1667067197343000","pactType":2,"pactCode":1,"state":{"onOff":1,"brightness":96,"colorTemInKelvin":0,"color":{"r":0,"g":4,"b":255},"mode":21,"result":1},"op":{"command":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZAAE/2QABP9kAAT/ZAAE/w4=","qqUCZAAE/2QABP9kAAT/ZAAE/w0=","qqUDZAAE/2QABP9kAAT/ZAAE/ww=","qhEAZAoKAAAAAAAAAAAAAAAAAN8=","qhIAZAgAAB4AAAAAAAAAAAAAAMo=","qiP/AAwAAAAAAIAAAACAAAAAgPo=","qjMRAAAAAAAAAAAAAAAAAAAAAIg="]}}].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] [AWS] receiving update {"onOff":1,"brightness":96,"colorTemInKelvin":0,"color":{"r":0,"g":4,"b":255},"mode":21,"result":1,"source":"AWS","commands":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZAAE/2QABP9kAAT/ZAAE/w4=","qqUCZAAE/2QABP9kAAT/ZAAE/w0=","qqUDZAAE/2QABP9kAAT/ZAAE/ww=","qhEAZAoKAAAAAAAAAAAAAAAAAN8=","qhIAZAgAAB4AAAAAAAAAAAAAAMo=","qiP/AAwAAAAAAIAAAACAAAAAgPo=","qjMRAAAAAAAAAAAAAAAAAAAAAIg="]}.
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] current brightness [38%].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qgUVAQAAAAAAAAAAAAAAAAAAALs=] [aa051501000000000000000000000000000000bb].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qqUBZAAE/2QABP9kAAT/ZAAE/w4=] [aaa501640004ff640004ff640004ff640004ff0e].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qqUCZAAE/2QABP9kAAT/ZAAE/w0=] [aaa502640004ff640004ff640004ff640004ff0d].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qqUDZAAE/2QABP9kAAT/ZAAE/ww=] [aaa503640004ff640004ff640004ff640004ff0c].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qhEAZAoKAAAAAAAAAAAAAAAAAN8=] [aa1100640a0a00000000000000000000000000df].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qhIAZAgAAB4AAAAAAAAAAAAAAMo=] [aa1200640800001e0000000000000000000000ca].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qiP/AAwAAAAAAIAAAACAAAAAgPo=] [aa23ff000c0000000000800000008000000080fa].
[29/10/2022, 19:13:18] [Govee] [Bedroom Lights] new scene code: [qjMRAAAAAAAAAAAAAAAAAAAAAIg=] [aa33110000000000000000000000000000000088].

```

**Comment by bwp91** [comment]
Hi @MattJGH 

Please update to the beta version of the plugin. This should be fixed!

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by samemory** [comment]
Hi @bwp91 I tried the beta version (beta-10) and am still having this issue. Whatever brightness I set it to in the Apple Home app only stays for a second and then it sets itself to a lower brightness.
Example: set to 70% but it sets it to 28% 
```
[12/11/2022, 13:32:06] [Govee] [H61A0_E908] [LAN] sending update [{"msg":{"cmd":"brightness","data":{"value":70}}}].
[12/11/2022, 13:32:06] [Govee] [H61A0_E908] [LAN] command sent to [192.168.0.xx]..
[12/11/2022, 13:32:06] [Govee] [H61A0_E908] current brightness [70%].
[12/11/2022, 13:32:06] [Govee] [AWS] message event [{"proType":2,"sku":"H61A0","device":"xxxxxx","softVersion":"2.06.06","wifiSoftVersion":"2.05.08","wifiHardVersion":"1.02.00","cmd":"brightness","type":0,"transaction":"v_1668281525684000","pactType":2,"pactCode":1,"state":{"brightness":70,"result":1}}].
[12/11/2022, 13:32:06] [Govee] [H61A0_E908] [AWS] receiving update {"source":"AWS","brightness":70,"result":1}.
[12/11/2022, 13:32:06] [Govee] [H61A0_E908] current brightness [28%].
```
I have LAN enabled. Product model is: H61A0

**Comment by bwp91** [comment]
@samemory 
please try beta 13

**Comment by SJNix** [comment]
I'm currently getting the same issue with v7.1.6 where my lights are set to %100 but are reporting %39 in Apple Home

**Comment by bwp91** [comment]
> I'm currently getting the same issue with v7.1.6 where my lights are set to %100 but are reporting %39 in Apple Home

need to know model

**Comment by SJNix** [comment]
Ah sorry these are H619C's

**Comment by bwp91** [comment]
> Ah sorry these are H619C's

and does colour changing still work?

**Comment by SJNix** [comment]
> > Ah sorry these are H619C's
> 
> and does colour changing still work?

Yes the colour changing works through the Home app

**Comment by bwp91** [comment]
cool i will sort the brightness issue out when i get home again 👍🏻

**Comment by bwp91** [comment]
@SJNix please check v7.1.7 :)

**Comment by SJNix** [comment]
Works, thanks!

**Comment by SJNix** [comment]
Actually, now that I'm playing around with air a bit @bwp91 it seems like maybe something is off with the colour changing. I can browse around using the colour wheel and pick a colour I'm happy with, however when I select a different colour preset in the Home app and back to the one I had chosen it kind of drifts to a different colour.

For example I'm looking for a light gold warm light setting, I get one I'm happy with but seems like it ends up drifting to more of a red colour.

**Comment by bwp91** [comment]
the device itself drifts or the colour shown in the home app! (or even both?!)

**Comment by SJNix** [comment]
It strangely seems like both, I did a screen recording of what happens in the Home app where you can see how it pops to a different colour, and the lights seem to react the same way slowly blending from the colour I set to the colour it pops to, hopefully the upload works
https://user-images.githubusercontent.com/19943764/202870630-39efdd52-5323-4fdf-9989-0e36f64ee60f.MP4

![RPReplay_Final1668889418 2](https://user-images.githubusercontent.com/19943764/202870873-065f1c29-701d-4e22-81f4-b77c9ba3b599.gif)

**Comment by kaltreuter** [comment]
I'm still having the same issue with the H7050 lights not showing the correct brightness on the home app even after updating to 7.1.7

**Comment by bwp91** [comment]
> I'm still having the same issue with the H7050 lights not showing the correct brightness on the home app even after updating to 7.1.7

Hi @kaltreuter I did not know this model did this too. Please try beta version `7.1.8-beta.1`

**Comment by kaltreuter** [comment]
> > I'm still having the same issue with the H7050 lights not showing the correct brightness on the home app even after updating to 7.1.7
> 
> Hi @kaltreuter I did not know this model did this too. Please try beta version `7.1.8-beta.1`

I tried the Beta and everything seems to be working now with the H7050s.  Thanks

**Comment by wsd11** [comment]
This looks to be an issue for the H6071 too on plug-in version 7.7.1 - color temperature changes don’t work, and Govee app brightness seems to correspond to 39% on the Home app.  

Making changes in the Govee app seems to reflect in Home, but Home changes don’t seem to make it to the light.

**Comment by bwp91** [comment]
@wsd11 please install beta version of plugin to see if this fixes things

**Comment by chrisleicester** [comment]
I’m still seeing this issue on v10.8.0. Any word on a fix?

**Comment by chrisleicester** [comment]
Never mind. Fixed with this: https://github.com/bwp91/homebridge-govee/wiki/Common-Errors
