### ISSUE TITLE
[BLE] could not start sync as Could not start scanning, state is unknown (not poweredOn) at Noble.scan

### ISSUE THREAD

**Issue by jamesdrake101** [bwp91/homebridge-govee#973]
### What issue do you have? Please be as thorough and explicit as possible.

Bluetooth LE scanning fails with this error message: `[Govee] [BLE] could not start sync as Could not start scanning, state is unknown (not poweredOn) at Noble.scan (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/@abandonware/noble/lib/noble.js:124:21).`

### Details of your setup.

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? **Homebridge web UI, not sure what "-X" is.**

* Which version of Homebridge/HOOBS do you have? **v1.8.5**

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known. **Linux 6.6.62+rpt-rpi-2712 arm64, Node.js v20.18.0**

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version? **10.12.1**

* Which Govee devices do you have that are causing issues? Please include product models if applicable. **All of them. Bluetooth scanning does not work.**

### Please paste any relevant logs below.

```
[03/12/2024, 10:29:46] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[03/12/2024, 10:34:46] [Govee] [BLE] could not start sync as Could not start scanning, state is unknown (not poweredOn) at Noble.scan (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/@abandonware/noble/lib/noble.js:124:21).
```

Worked just fine only days ago. Not sure what happened.

Thanks!

**Comment by jamesdrake101** [comment]
Possibly related: https://github.com/abandonware/noble/issues/345

**Comment by jamesdrake101** [comment]
Downgraded Raspbian kernel to `d5a7dbe77b71974b9abb133a4b5210a8070c9284` (aka `6.6.51-v8-16k+`) and everything is back to normal.

```
sudo rpi-update d5a7dbe77b71974b9abb133a4b5210a8070c9284
```

Clearly a recent kernel update bricked Bluetooth.

**Comment by Busyrev** [comment]
Just for information, there is a a fix from bluetooth-hci-socket side. See https://github.com/stoprocent/noble/issues/4

**Comment by weissk93** [comment]
> Downgraded Raspbian kernel to `d5a7dbe77b71974b9abb133a4b5210a8070c9284` (aka `6.6.51-v8-16k+`) and everything is back to normal.
> 
> ```
> sudo rpi-update d5a7dbe77b71974b9abb133a4b5210a8070c9284
> ```
> 
> Clearly a recent kernel update bricked Bluetooth.

I try to run this and it says command not found. Any thoughts?

**Comment by jamesdrake101** [comment]
@weissk93 That tool may not be installed by default on Raspbian. I honestly don't remember. But you should be able to install it following the instructions here: https://github.com/raspberrypi/rpi-update
By the way, I think it's possible to wreck everything if you mess around with that tool - tread carefully.

**Comment by jamesdrake101** [comment]
> Just for information, there is a a fix from bluetooth-hci-socket side. See [stoprocent/noble#4](https://github.com/stoprocent/noble/issues/4)

@bwp91  Any way to port this fix into the `noble.js` bundled inside `homebridge-govee`? Thanks.

**Comment by jamesdrake101** [comment]
@bwp91 Bump.
I constantly have to make sure I don't update the kernel ...

**Comment by mmenanno** [comment]
I'm getting this same error, but I'm using Homebridge 1.9.0, dockerized with Ubuntu Noble (24.04.1 LTS). My plugin version is v10.17.0. Is there something I can update to get this fixed for me as well?

```
[4/3/2025, 2:37:30 PM] [Govee] [BLE] could not start sync as Could not start scanning, state is poweredOff (not poweredOn) at Noble.scan (/homebridge/node_modules/@homebridge-plugins/homebridge-govee/node_modules/@abandonware/noble/lib/noble.js:124:21).
```

**Comment by fwunder** [comment]
Same error. 

macOS Monterey (12.7.6) Homebridge v1.9.0  Homnbridge Govee v11.0.2  Node.js v22.16.0

`[BLE] could not start sync as Could not start scanning, state is unauthorized (not poweredOn) at Noble.scan (/usr/local/lib/node_modules/@homebridge-plugins/homebridge-govee/node_modules/@stoprocent/noble/lib/noble.js:159:21).`

**Comment by josephveit** [comment]
> Same error.
> 
> macOS Monterey (12.7.6) Homebridge v1.9.0 Homnbridge Govee v11.0.2 Node.js v22.16.0
> 
> `[BLE] could not start sync as Could not start scanning, state is unauthorized (not poweredOn) at Noble.scan (/usr/local/lib/node_modules/@homebridge-plugins/homebridge-govee/node_modules/@stoprocent/noble/lib/noble.js:159:21).`

I've been running Homebridge on macOS 15 for a while and just recently added the Homebridge Govee plugin and run into this error.

I think I've fixed it by going to System Settings > Privacy & Security > Bluetooth and adding Node to the allowed applications list.

I don't recall if Monterey had all the same types of restrictions, but if so, you may need to make a similar change on your system.

**Comment by fwunder** [comment]
> > Same error.
> > macOS Monterey (12.7.6) Homebridge v1.9.0 Homnbridge Govee v11.0.2 Node.js v22.16.0
> > `[BLE] could not start sync as Could not start scanning, state is unauthorized (not poweredOn) at Noble.scan (/usr/local/lib/node_modules/@homebridge-plugins/homebridge-govee/node_modules/@stoprocent/noble/lib/noble.js:159:21).`
> 
> I've been running Homebridge on macOS 15 for a while and just recently added the Homebridge Govee plugin and run into this error.
> 
> I think I've fixed it by going to System Settings > Privacy & Security > Bluetooth and adding Node to the allowed applications list.
> 
> I don't recall if Monterey had all the same types of restrictions, but if so, you may need to make a similar change on your system.

Thanks, but I can't figure out how to add /usr/local/bin/node to allowed applications. I don't believe there is a command line option. I reinstalled Node.js from pkg and still get same error. Thanks again.

**Comment by fwunder** [comment]
I did figure out how to add Node to  System Settings > Privacy & Security > Bluetooth .

Error remains.

**Comment by SemoTech** [comment]
I had a similar issue and it was due to the node module the Govee Homebridge plugin was using.  A quick edit fixed it but it should be integrated into the next version.  Hope this helps:  https://github.com/homebridge-plugins/homebridge-govee/issues/1150
